// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = require('./lib/Notificator');

  module.exports.Channel = require('./lib/NotificatorChannel');

  module.exports.EmailChannel = require('./lib/channels/EmailChannel');

}).call(this);
