// Generated by CoffeeScript 1.10.0
(function() {
  var Notificator, async, util,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  async = require('async');

  util = require('util');

  Notificator = (function() {
    Notificator.prototype.defaultLanguage = 'en';

    Notificator.prototype.channels = [];

    Notificator.prototype.events = [];

    function Notificator(options1) {
      this.options = options1 != null ? options1 : {};
    }

    Notificator.prototype.registerEvent = function(event) {
      return this.events.push(event);
    };

    Notificator.prototype.registerEvents = function(events) {
      var event, i, len, results;
      results = [];
      for (i = 0, len = events.length; i < len; i++) {
        event = events[i];
        results.push(this.registerEvent(event));
      }
      return results;
    };

    Notificator.prototype.addChannel = function(name, channel) {
      return this.channels.push({
        name: name,
        channel: channel
      });
    };

    Notificator.prototype.getTemplate = function(messageId, channel, language, callback) {
      return channel.getTemplate(messageId, language, function(err, message) {
        if (err) {
          return callback(err);
        }
        return callback(null, message);
      });
    };

    Notificator.prototype.parseTemplate = function(template, receiver, data) {
      data = data || {};
      data.receiver = receiver;
      return template.parsedData(data);
    };

    Notificator.prototype.notify = function(event, receiver, data, options, callback) {
      if (typeof data === 'function') {
        callback = data;
        data = options = void 0;
      } else if (typeof options === 'function') {
        callback = options;
        options = void 0;
      }
      if (indexOf.call(this.events, event) < 0) {
        return callback(new Error('unknown event ' + event));
      }
      console.log(event, receiver, data, options, callback);
      data = data || {};
      return async.forEach(this.channels, (function(_this) {
        return function(channel, cb) {
          var _channel, ref;
          if (util.isArray(_this.options.channels) && (ref = channel.name, indexOf.call(_this.options.channels, ref) < 0)) {
            return cb();
          }
          _channel = channel.channel;
          return _channel.getDestinations(receiver, function(err, destinations) {
            if (err) {
              return cb(err);
            }
            return async.forEach(destinations, function(destination, cb) {
              return _this.getTemplate(event, _channel, destination.language || _this.defaultLanguage, function(err, event) {
                var message;
                if (err) {
                  return cb(err);
                }
                message = _this.parseTemplate(event, receiver, data);
                console.log(message, destination);
                return channel.channel.sendMessage(message, destination, cb);
              });
            }, cb);
          });
        };
      })(this), callback);
    };

    return Notificator;

  })();

  module.exports = Notificator;

}).call(this);
